// Generated by CoffeeScript 1.7.1
(function() {
  var User, app, express, mongoose, path;

  express = require('express');

  path = require('path');

  mongoose = require('mongoose');

  mongoose.connect("mongodb://localhost:27017/coffee-express");

  app = express();

  app.use(express["static"](__dirname + "/public"));

  app.use(express.bodyParser());

  app.set('view engine', 'ejs');

  app.set('views', path.join(__dirname, 'views'));

  User = require('./models/user')(mongoose);

  app.get('/register', function(req, res) {
    var account, email, password;
    account = req.query.account;
    password = req.query.password;
    email = req.query.email;
    if (!account || !password || !email) {
      res.render("index", {
        title: 'error',
        content: 'tttt'
      });
    } else {
      User.register(email, password, account, function(data) {
        return console.log(data);
      });
      res.render("index", {
        title: 'register',
        content: 'tttt'
      });
    }
    return console.log("visited");
  });

  app.get('/login', function(req, res) {
    User.login('dffg', 'ddfgd', function(data) {
      return console.log(data);
    });
    res.render("index", {
      title: 'login',
      content: 'tttt'
    });
    return console.log("login");
  });

  app.get('/update', function(req, res) {
    User.update('kkg', 'ddfgdddffsssddd', function(err, data) {
      return console.log(data);
    });
    res.render("index", {
      title: 'update',
      content: 'tttt'
    });
    return console.log("update");
  });

  app.get('/delete', function(req, res) {
    User.deleteUser('kkg', function(err, data) {
      return console.log(data);
    });
    res.render("index", {
      title: 'delete',
      content: 'tttt'
    });
    return console.log("delete");
  });

  app.listen(3000);

  console.log("Express server listening on port %d in %s mode");

}).call(this);

//# sourceMappingURL=app.map
