// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(mongoose) {
    var User, UserScheme, crypto, register, registerCallback;
    crypto = require('crypto');
    UserScheme = new mongoose.Schema({
      email: {
        type: String,
        unique: true
      },
      account: {
        type: String,
        unique: true
      },
      password: {
        type: String
      }
    });
    User = mongoose.model('User', UserScheme);
    registerCallback = function(err) {
      if (err) {
        return console.log(err);
      }
      return console.log('new account added');
    };
    register = function(email, password, account) {
      var shaSum, user;
      shaSum = crypto.createHash('sha256');
      shaSum.update(password);
      console.log('register' + email);
      user = new User({
        email: email,
        password: password,
        account: account
      });
      user.save(registerCallback);
    };
    return {
      register: register,
      User: User
    };
  };

}).call(this);

//# sourceMappingURL=user.map
